### ISSUE TITLE
Remove RE2 dep

### ISSUE THREAD

**Issue by brandonhorst** [silentrob/normalizer#5]
RE2 dep breaks the ability to run in non-node environments (like the browser).

Tests pass just fine with using normal `RegExp` objects. I have the code - would you accept a PR?

**Comment by silentrob** [comment]
So my primary motivation to use RE2 over RegExp was for performance. Have you noticed a difference between the two?

**Comment by brandonhorst** [comment]
No, I didn't do any profiling. It makes sense that performance would be better.

**Comment by silentrob** [comment]
Do you think it would be possible to support both, should I revert it or do you want to fork it?

**Comment by brandonhorst** [comment]
So it turns out that for my application, I am going to need to fork it anyway (because I the `~emohappy` stuff won't work for my purposes). So from my point of view, it can stay the way it is if it works for SuperScript. Thanks for the great code and data!

**Comment by silentrob** [comment]
If you end up making any major changes that might improve this code base please let me know and Ill be happy to merge them back!
